AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tp2

  CRUD lambda dynamo BD

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Runtime: python3.8
    MemorySize: 1028

Parameters:
  Table:
    Type: String
    Default: Article
  Region:
    Type: String
    Default: eu-west-3

Resources:

  MyCountry:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/layers/my_country
      CompatibleRuntimes:
        - python3.8
    #Metadata : 
    #  BuildMethod : python3.8

  getCountryFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/country/get
      Handler: app.lambda_handler
      Events:
        ApiG:
          Type: Api
          Properties:
            Path: /country
            Method: get
      Layers:
        - !Ref MyCountry

Outputs:
  countryApi:
    Description: "API Gateway endpoint URL for Prod stage for article function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/country/"
  articleFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt getCountryFunction.Arn